version: '3.9'

services:
  frontend:
    image: giperpetr/giperarena-frontend:latest
    container_name: giperarena-frontend
    restart: unless-stopped
    env_file:
      - gipergiraffe.com.env
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - default
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.giperarena.rule=Host(`giperarena.space`) || Host(`www.giperarena.space`)"
      - "traefik.http.routers.giperarena.entrypoints=websecure"
      - "traefik.http.routers.giperarena.tls.certresolver=letsencrypt"
      - "traefik.http.services.giperarena.loadbalancer.server.port=3000"

  backend:
    image: giperpetr/giperarena-backend:latest
    container_name: giperarena-backend
    restart: unless-stopped
    env_file:
      - gipergiraffe.com.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - default
      - proxy
      - supabase_default
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.giperarena-api.rule=Host(`api.giperarena.space`)"
      - "traefik.http.routers.giperarena-api.entrypoints=websecure"
      - "traefik.http.routers.giperarena-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.giperarena-api.loadbalancer.server.port=3000"

networks:
  default:
    driver: bridge
  proxy:
    external: true
  supabase_default:
    external: true
